spring.application.name=mcgill-menu-prices

spring.datasource.url=jdbc:postgresql://localhost:5432/mcgill_menu_prices
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
